Algoritmo "contar1a10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/06/2025
Var
    cont: Inteiro

Inicio
    cont <-1
    Repita
          Escreval(cont)
          cont <- cont + 1
    Ate (cont > 10 )

Fimalgoritmo